name: reset demo

on:
  workflow_dispatch:

jobs:
  
  reset_demo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6.1.0
        with:
          ref: ${{vars.pr_from_branch}}
      
      - name: generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.app_client_id }}
          private-key: ${{ secrets.app_private_key }}
      
      - name: close existing pr (if open)
        run: gh pr close '${{vars.pr_from_branch}}'
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.CREATE_PR_TOKEN }}
      
      - name: create pr
        run: gh pr create --assignee '${{vars.pr_author}}' --base main --body '${{vars.pr_body}}' -H '${{vars.pr_from_branch}}' --title '${{vars.pr_title}}'
        env:
          GH_TOKEN: ${{ secrets.CREATE_PR_TOKEN }}
      
      - name: get pr number
        id: get_pr_number
        run: |
          PR_NUM=$(gh pr list --head ${{vars.pr_from_branch}} --state open --json number --jq '.[0] | .number')
          echo "pr_number=$PR_NUM" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.CREATE_PR_TOKEN }}
      
      - name: add bot reply
        uses: peter-evans/create-or-update-comment@v5.0.0
        with:
          token: ${{ steps.generate_token.outputs.token }}
          issue-number: ${{ steps.get_pr_number.outputs.pr_number }}
          body: ${{ vars.pr_initial_reply }}
